import './index.html';
import './index.scss';
import "./modules/modalWindows.js";
import "./modules/hideShow-brands.js";
import "./modules/swiper-brands.js";
import "./modules/hideShow-devices.js";
import "./modules/swiper-devices.js";
import "./modules/readMore.js";
import "./modules/swiper-table.js"
